<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'EdpGithub\Module'                               => __DIR__ . '/Module.php',
    'EdpGithub\Service\UserGithub'                   => __DIR__ . '/src/EdpGithub/Service/UserGithub.php',
    'EdpGithub\Model\UserGithub'                     => __DIR__ . '/src/EdpGithub/Model/UserGithub.php',
    'EdpGithub\ApiClient\Service\AbstractService'    => __DIR__ . '/src/EdpGithub/ApiClient/Service/AbstractService.php',
    'EdpGithub\ApiClient\Service\User'               => __DIR__ . '/src/EdpGithub/ApiClient/Service/User.php',
    'EdpGithub\ApiClient\Model\User'                 => __DIR__ . '/src/EdpGithub/ApiClient/Model/User.php',
    'EdpGithub\ApiClient\ApiClient'                  => __DIR__ . '/src/EdpGithub/ApiClient/ApiClient.php',
    'EdpGithub\Mapper\UserGithubZendDb'              => __DIR__ . '/src/EdpGithub/Mapper/UserGithubZendDb.php',
    'EdpGithub\Authentication\Adapter\ZfcUserGithub' => __DIR__ . '/src/EdpGithub/Authentication/Adapter/ZfcUserGithub.php',
);